# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o1psO-qifBrFm99zTivBtNYwdY1VS6q1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/retail_sales_dataset.csv")
df.head()

df.info()
df.describe()

df.isnull().sum()
df.duplicated().sum()

df['Date'] = pd.to_datetime(df['Date'])

df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

df['Total Amount'].mean()
df['Total Amount'].median()
df['Total Amount'].mode()
df['Total Amount'].std()

monthly_sales = df.groupby('Date')['Total Amount'].sum()
monthly_sales.plot(figsize=(12,6))
plt.title("Sales Trend Over Time")
plt.show()

monthly_sales = df.resample('ME', on='Date')['Total Amount'].sum()
monthly_sales.plot()

df.groupby('Customer ID')['Total Amount'].sum().sort_values(ascending=False).head(10)
df.groupby('Gender')['Total Amount'].mean()
df.groupby('Product Category')['Total Amount'].sum().sort_values(ascending=False)
sns.barplot(x='Product Category', y='Total Amount', data=df)
plt.xticks(rotation=45)
plt.show()

sns.lineplot(data=monthly_sales)

sns.barplot(x='Product Category', y='Total Amount', data=df)
plt.xticks(rotation=45)
plt.show()

sns.heatmap(df.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm')
plt.show()

sns.boxplot(x='Product Category', y='Total Amount', data=df)

